### ISSUE TITLE
Not working on server :c version 1.18.2 

### ISSUE THREAD

**Issue by alexaddee23** [croissantnova/SanityDescentIntoMadness#1]
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 21/6/23 14:13
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.18.2-40.2.0-universal.jar%23190!/:?] {re:classloading}
	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:39) ~[forge-1.18.2-40.2.0-universal.jar%23190!/:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:112) ~[server-1.18.2-20220404.173914-srg.jar%23185!/:?] {re:classloading,re:mixin,pl:mixin:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:32) ~[fmlloader-1.18.2-40.2.0.jar%2317!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
-- MOD sanitydim --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: org/apache/commons/compress/utils/Lists
		at croissantnova.sanitydim.config.ConfigDefault.<init>(ConfigDefault.java:117) ~[sanitydim-mc1.18-1.0.0.jar%23144!/:1.0.0] {re:classloading}
		at net.minecraftforge.common.ForgeConfigSpec$Builder.configure(ForgeConfigSpec.java:615) ~[forge-1.18.2-40.2.0-universal.jar%23190!/:?] {re:classloading}
		at croissantnova.sanitydim.config.ConfigHandler.init(ConfigHandler.java:26) ~[sanitydim-mc1.18-1.0.0.jar%23144!/:1.0.0] {re:classloading}
		at croissantnova.sanitydim.SanityMod.<clinit>(SanityMod.java:53) ~[sanitydim-mc1.18-1.0.0.jar%23144!/:1.0.0] {re:classloading,pl:runtimedistcleaner:A}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[javafmllanguage-1.18.2-40.2.0.jar%23187!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[fmlcore-1.18.2-40.2.0.jar%23186!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}

	Mod File: /C:/Users/john/Desktop/Nueva carpeta (13)/mods/sanitydim-mc1.18-1.0.0.jar
	Failure message: Sanity: Descent Into Madness (sanitydim) has failed to load correctly
		java.lang.NoClassDefFoundError: org/apache/commons/compress/utils/Lists
	Mod Version: 1.0.0
	Mod Issue URL: https://github.com/croissantnova/SanityDescentIntoMadness/issues
	Exception message: java.lang.ClassNotFoundException: org.apache.commons.compress.utils.Lists
Stacktrace:
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134) ~[securejarhandler-1.0.3.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134) ~[securejarhandler-1.0.3.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at croissantnova.sanitydim.config.ConfigDefault.<init>(ConfigDefault.java:117) ~[sanitydim-mc1.18-1.0.0.jar%23144!/:1.0.0] {re:classloading}
	at net.minecraftforge.common.ForgeConfigSpec$Builder.configure(ForgeConfigSpec.java:615) ~[forge-1.18.2-40.2.0-universal.jar%23190!/:?] {re:classloading}
	at croissantnova.sanitydim.config.ConfigHandler.init(ConfigHandler.java:26) ~[sanitydim-mc1.18-1.0.0.jar%23144!/:1.0.0] {re:classloading}
	at croissantnova.sanitydim.SanityMod.<clinit>(SanityMod.java:53) ~[sanitydim-mc1.18-1.0.0.jar%23144!/:1.0.0] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[javafmllanguage-1.18.2-40.2.0.jar%23187!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[fmlcore-1.18.2-40.2.0.jar%23186!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}

PD: I also tried with the newer version

**Comment by croissantnova** [comment]
What Java version are you using?

**Comment by alexaddee23** [comment]
Java 8 update 317  (8.0.3710.11)
And Forge 40.2.0 (Minecraft 1.18.2)

**Comment by croissantnova** [comment]
Minecraft 1.18+ uses Java 17+. Please update and see if it fixes the error.

**Comment by PunCakeCat** [comment]
i used forge server 40.2.4 and java 17 having the same issue.

**Comment by croissantnova** [comment]
I'm not sure where this library comes from. I'll remove all references to it, it's not a huge deal, but something tells me this isn't the way this issue is supposed to be resolved.

**Comment by croissantnova** [comment]
Try running a server with [this](https://github.com/croissantnova/SanityDescentIntoMadness/releases/tag/v1.0.2-alpha) version.

**Comment by alexaddee23** [comment]
It worked for me, I thought it was a waste not to use this mod in my server, this mod is just insane well done.

**Comment by croissantnova** [comment]
Great!
