### ISSUE TITLE
[1.20.1 - 1.0.0] Server Crash on Startup with Mod

### ISSUE THREAD

**Issue by samjviana** [croissantnova/SanityDescentIntoMadness#4]
I've encountered an issue while trying to run a Minecraft server with the mod.
Unfortunately, the server crashes during the startup process and I'm unable to get it running.
The error message I receive is "Sanity: Descent Into

Here's some additional information that might help you diagnose the problem:

- I'm running Minecraft version 1.20.1.
- The version of your mod I'm using is 1.0.0.
- I've tried running the server with only your mod installed to ensure there are no conflicts with other mods.
- I've attached the server log below for your reference. Madness (sanitydim) has failed to load correctly".
<details>
  <summary><code>latest.log</code></summary>

```
[28jun.2023 21:18:04.303] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 47.0.19, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412]
[28jun.2023 21:18:04.310] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 17.0.7 by Eclipse Adoptium; OS Windows 11 arch amd64 version 10.0
[28jun.2023 21:18:04.589] [main/INFO] [net.minecraftforge.fml.loading.ImmediateWindowHandler/]: ImmediateWindowProvider not loading because launch target is forgeserver
[28jun.2023 21:18:04.708] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/samjv/Desktop/minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2365!/ Service=ModLauncher Env=SERVER
[28jun.2023 21:18:05.089] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\samjv\Desktop\minecraft\libraries\net\minecraftforge\fmlcore\1.20.1-47.0.19\fmlcore-1.20.1-47.0.19.jar is missing mods.toml file
[28jun.2023 21:18:05.096] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\samjv\Desktop\minecraft\libraries\net\minecraftforge\javafmllanguage\1.20.1-47.0.19\javafmllanguage-1.20.1-47.0.19.jar is missing mods.toml file
[28jun.2023 21:18:05.103] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\samjv\Desktop\minecraft\libraries\net\minecraftforge\lowcodelanguage\1.20.1-47.0.19\lowcodelanguage-1.20.1-47.0.19.jar is missing mods.toml file
[28jun.2023 21:18:05.108] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\samjv\Desktop\minecraft\libraries\net\minecraftforge\mclanguage\1.20.1-47.0.19\mclanguage-1.20.1-47.0.19.jar is missing mods.toml file
[28jun.2023 21:18:05.234] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator/]: No dependencies to load found. Skipping!
[28jun.2023 21:18:07.563] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[28jun.2023 21:18:07.569] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeserver' with arguments []
[28jun.2023 21:18:07.808] [main/ERROR] [net.minecraftforge.fml.loading.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/renderer/GameRenderer for invalid dist DEDICATED_SERVER
[28jun.2023 21:18:07.809] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/renderer/GameRenderer (java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/GameRenderer for invalid dist DEDICATED_SERVER)
[28jun.2023 21:18:07.810] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.renderer.GameRenderer was not found sanitydim.mixins.json:MixinGameRenderer
[28jun.2023 21:18:19.386] [modloading-worker-0/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: sanitydim, class croissantnova.sanitydim.SanityMod
java.lang.NoClassDefFoundError: org/apache/commons/compress/utils/Lists
	at croissantnova.sanitydim.config.ConfigDefault.<init>(ConfigDefault.java:117) ~[sanitydim-mc1.20-1.0.0.jar%23103!/:1.0.0]
	at net.minecraftforge.common.ForgeConfigSpec$Builder.configure(ForgeConfigSpec.java:605) ~[forge-1.20.1-47.0.19-universal.jar%23110!/:?]
	at croissantnova.sanitydim.config.ConfigHandler.init(ConfigHandler.java:26) ~[sanitydim-mc1.20-1.0.0.jar%23103!/:1.0.0]
	at croissantnova.sanitydim.SanityMod.<clinit>(SanityMod.java:53) ~[sanitydim-mc1.20-1.0.0.jar%23103!/:1.0.0]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.20.1-47.0.19.jar%23107!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.0.19.jar%23106!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.apache.commons.compress.utils.Lists
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 18 more
[28jun.2023 21:18:19.395] [modloading-worker-0/INFO] [net.minecraftforge.common.ForgeMod/FORGEMOD]: Forge mod loading, version 47.0.19, for MC 1.20.1 with MCP 20230612.114412
[28jun.2023 21:18:19.406] [modloading-worker-0/INFO] [net.minecraftforge.common.MinecraftForge/FORGE]: MinecraftForge v47.0.19 Initialized
[28jun.2023 21:18:19.678] [main/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event CONSTRUCT, 1 errors found
[28jun.2023 21:18:19.918] [main/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 137cfea9-754e-4f55-b332-3c14765bb74e
[28jun.2023 21:18:19.920] [main/FATAL] [net.minecraftforge.server.loading.ServerModLoader/]: Crash report saved to .\crash-reports\crash-2023-06-28_21.18.19-fml.txt
[28jun.2023 21:18:19.924] [main/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 7a82103b-8df9-4516-8e74-268552c05379
[28jun.2023 21:18:19.932] [main/ERROR] [net.minecraft.server.Main/FATAL]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	Sanity: Descent Into Madness (sanitydim) has failed to load correctly
§7java.lang.NoClassDefFoundError: org/apache/commons/compress/utils/Lists
]
	at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:246) ~[fmlcore-1.20.1-47.0.19.jar%23106!/:?]
	at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$20(ModLoader.java:210) ~[fmlcore-1.20.1-47.0.19.jar%23106!/:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:210) ~[fmlcore-1.20.1-47.0.19.jar%23106!/:?]
	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$13(ModLoader.java:183) ~[fmlcore-1.20.1-47.0.19.jar%23106!/:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:183) ~[fmlcore-1.20.1-47.0.19.jar%23106!/:?]
	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:32) ~[forge-1.20.1-47.0.19-universal.jar%23110!/:?]
	at net.minecraft.server.Main.main(Main.java:125) ~[server-1.20.1-20230612.114412-srg.jar%23105!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.0.19.jar%2369!/:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103) ~[fmlloader-1.20.1-47.0.19.jar%2369!/:?]
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27) ~[fmlloader-1.20.1-47.0.19.jar%2369!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar%2355!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar%2355!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar%2355!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar%2355!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar%2355!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar%2355!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar%2355!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
```

</details>

I hope this information is helpful. I'm really excited to use your mod on my server and I appreciate any assistance you can provide to resolve this issue.

Thank you in advance for your time and help!

**Comment by croissantnova** [comment]
This is a known bug that seems to affect versions from mc1.18 to mc1.20. I'll fully fix it with the next big mod release. For the time being, use [this version](https://github.com/croissantnova/SanityDescentIntoMadness/releases/tag/v1.0.1-alpha) and see if it fixes the error.

**Comment by samjviana** [comment]
I've just tested it and the server is starting up correctly.
I'll continue to use the mod and will keep an eye out for any other issues.
If you want, you can close this issue.

**Comment by croissantnova** [comment]
Fixed in mc1.20-v1.1.0.
